apiVersion: v1
kind: Service
metadata: 
  name: roxie
  labels: 
     app: roxie
spec: 
  ports: 
    - name: roxie
      protocol: TCP
      port: 9876
      targetPort: 9876 
  selector: 
     app: roxie
  type: LoadBalancer
